version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'kursach'
      MYSQL_USER: 'rafikov'
      MYSQL_PASSWORD: 'kursach'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
  flask:
    depends_on:
      - db
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - .:/app
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
