FROM python:3.7
ENV APP /server
COPY /server /app
WORKDIR /app
EXPOSE 5000
COPY requirements.txt requirements.txt
COPY wait_for.sh wait_for.sh
RUN pip install -r requirements.txt
CMD [ "uwsgi", "--ini", "config/server.ini" ]
